// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleUSER  UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Order struct {
	ID              string         `json:"id"`
	Canal           string         `json:"canal"`
	Cantidad        int32          `json:"cantidad"`
	Company         string         `json:"company"`
	Cp              string         `json:"cp"`
	CreatedAt       string         `json:"created_at"`
	DaysToDelivery  sql.NullString `json:"days_to_delivery"`
	Error           sql.NullString `json:"error"`
	ErrorMessage    sql.NullString `json:"error_message"`
	FechaCompra     sql.NullString `json:"fecha_compra"`
	FechaEstimada   sql.NullString `json:"fecha_estimada"`
	FulfillmentType sql.NullString `json:"fulfillment_type"`
	IsFlash         bool           `json:"is_flash"`
	IsMarketplace   bool           `json:"is_marketplace"`
	NoPedido        sql.NullString `json:"no_pedido"`
	Plan            sql.NullString `json:"plan"`
	ProductType     sql.NullString `json:"product_type"`
	Sku             sql.NullString `json:"sku"`
	StoreSelected   sql.NullString `json:"store_selected"`
	TipoPago        sql.NullString `json:"tipo_pago"`
	Edd1            sql.NullString `json:"edd1"`
	Edd2            sql.NullString `json:"edd2"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
