// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*) FROM orders
WHERE 
    (canal = $1 OR $1 = '') AND
    (company = $2 OR $2 = '') AND
    (fulfillment_type = $3 OR $3 IS NULL OR $3 = '') AND
    (product_type = $4 OR $4 IS NULL OR $4 = '')
`

type CountOrdersParams struct {
	Canal           string         `json:"canal"`
	Company         string         `json:"company"`
	FulfillmentType sql.NullString `json:"fulfillment_type"`
	ProductType     sql.NullString `json:"product_type"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrders,
		arg.Canal,
		arg.Company,
		arg.FulfillmentType,
		arg.ProductType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
    id, canal, cantidad, company, cp, created_at, days_to_delivery, error, error_message,
    fecha_compra, fecha_estimada, fulfillment_type, is_flash, is_marketplace,
    no_pedido, plan, product_type, sku, store_selected, tipo_pago, edd1, edd2
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
) ON CONFLICT (id) DO NOTHING
`

type CreateOrderParams struct {
	ID              string         `json:"id"`
	Canal           string         `json:"canal"`
	Cantidad        int32          `json:"cantidad"`
	Company         string         `json:"company"`
	Cp              string         `json:"cp"`
	CreatedAt       string         `json:"created_at"`
	DaysToDelivery  sql.NullString `json:"days_to_delivery"`
	Error           sql.NullString `json:"error"`
	ErrorMessage    sql.NullString `json:"error_message"`
	FechaCompra     sql.NullString `json:"fecha_compra"`
	FechaEstimada   sql.NullString `json:"fecha_estimada"`
	FulfillmentType sql.NullString `json:"fulfillment_type"`
	IsFlash         bool           `json:"is_flash"`
	IsMarketplace   bool           `json:"is_marketplace"`
	NoPedido        sql.NullString `json:"no_pedido"`
	Plan            sql.NullString `json:"plan"`
	ProductType     sql.NullString `json:"product_type"`
	Sku             sql.NullString `json:"sku"`
	StoreSelected   sql.NullString `json:"store_selected"`
	TipoPago        sql.NullString `json:"tipo_pago"`
	Edd1            sql.NullString `json:"edd1"`
	Edd2            sql.NullString `json:"edd2"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.Canal,
		arg.Cantidad,
		arg.Company,
		arg.Cp,
		arg.CreatedAt,
		arg.DaysToDelivery,
		arg.Error,
		arg.ErrorMessage,
		arg.FechaCompra,
		arg.FechaEstimada,
		arg.FulfillmentType,
		arg.IsFlash,
		arg.IsMarketplace,
		arg.NoPedido,
		arg.Plan,
		arg.ProductType,
		arg.Sku,
		arg.StoreSelected,
		arg.TipoPago,
		arg.Edd1,
		arg.Edd2,
	)
	return err
}

const getDistinctCanals = `-- name: GetDistinctCanals :many
SELECT DISTINCT canal FROM orders ORDER BY canal
`

func (q *Queries) GetDistinctCanals(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctCanals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var canal string
		if err := rows.Scan(&canal); err != nil {
			return nil, err
		}
		items = append(items, canal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctCompanies = `-- name: GetDistinctCompanies :many
SELECT DISTINCT company FROM orders ORDER BY company
`

func (q *Queries) GetDistinctCompanies(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var company string
		if err := rows.Scan(&company); err != nil {
			return nil, err
		}
		items = append(items, company)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctFulfillmentTypes = `-- name: GetDistinctFulfillmentTypes :many
SELECT DISTINCT fulfillment_type FROM orders ORDER BY fulfillment_type
`

func (q *Queries) GetDistinctFulfillmentTypes(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctFulfillmentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var fulfillment_type sql.NullString
		if err := rows.Scan(&fulfillment_type); err != nil {
			return nil, err
		}
		items = append(items, fulfillment_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctProductTypes = `-- name: GetDistinctProductTypes :many
SELECT DISTINCT product_type FROM orders ORDER BY product_type
`

func (q *Queries) GetDistinctProductTypes(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctProductTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var product_type sql.NullString
		if err := rows.Scan(&product_type); err != nil {
			return nil, err
		}
		items = append(items, product_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByCanal = `-- name: GetOrdersByCanal :many
SELECT canal, COUNT(*) as count FROM orders GROUP BY canal
`

type GetOrdersByCanalRow struct {
	Canal string `json:"canal"`
	Count int64  `json:"count"`
}

func (q *Queries) GetOrdersByCanal(ctx context.Context) ([]GetOrdersByCanalRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByCanal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByCanalRow
	for rows.Next() {
		var i GetOrdersByCanalRow
		if err := rows.Scan(&i.Canal, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByFulfillmentType = `-- name: GetOrdersByFulfillmentType :many
SELECT fulfillment_type, COUNT(*) as count FROM orders GROUP BY fulfillment_type
`

type GetOrdersByFulfillmentTypeRow struct {
	FulfillmentType sql.NullString `json:"fulfillment_type"`
	Count           int64          `json:"count"`
}

func (q *Queries) GetOrdersByFulfillmentType(ctx context.Context) ([]GetOrdersByFulfillmentTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByFulfillmentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByFulfillmentTypeRow
	for rows.Next() {
		var i GetOrdersByFulfillmentTypeRow
		if err := rows.Scan(&i.FulfillmentType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByProductType = `-- name: GetOrdersByProductType :many
SELECT product_type, COUNT(*) as count FROM orders GROUP BY product_type
`

type GetOrdersByProductTypeRow struct {
	ProductType sql.NullString `json:"product_type"`
	Count       int64          `json:"count"`
}

func (q *Queries) GetOrdersByProductType(ctx context.Context) ([]GetOrdersByProductTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByProductType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByProductTypeRow
	for rows.Next() {
		var i GetOrdersByProductTypeRow
		if err := rows.Scan(&i.ProductType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersWithErrorsCount = `-- name: GetOrdersWithErrorsCount :one
SELECT COUNT(*) FROM orders WHERE error IS NOT NULL AND error <> '' AND error <> '0'
`

func (q *Queries) GetOrdersWithErrorsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrdersWithErrorsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalOrders = `-- name: GetTotalOrders :one
SELECT COUNT(*) FROM orders
`

func (q *Queries) GetTotalOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, canal, cantidad, company, cp, created_at, days_to_delivery, error, error_message, fecha_compra, fecha_estimada, fulfillment_type, is_flash, is_marketplace, no_pedido, plan, product_type, sku, store_selected, tipo_pago, edd1, edd2 FROM orders
WHERE 
    (canal = $1 OR $1 = '') AND
    (company = $2 OR $2 = '') AND
    (fulfillment_type = $3 OR $3 IS NULL OR $3 = '') AND
    (product_type = $4 OR $4 IS NULL OR $4 = '')
ORDER BY id
LIMIT $5 OFFSET $6
`

type ListOrdersParams struct {
	Canal           string         `json:"canal"`
	Company         string         `json:"company"`
	FulfillmentType sql.NullString `json:"fulfillment_type"`
	ProductType     sql.NullString `json:"product_type"`
	Limit           int32          `json:"limit"`
	Offset          int32          `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders,
		arg.Canal,
		arg.Company,
		arg.FulfillmentType,
		arg.ProductType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Canal,
			&i.Cantidad,
			&i.Company,
			&i.Cp,
			&i.CreatedAt,
			&i.DaysToDelivery,
			&i.Error,
			&i.ErrorMessage,
			&i.FechaCompra,
			&i.FechaEstimada,
			&i.FulfillmentType,
			&i.IsFlash,
			&i.IsMarketplace,
			&i.NoPedido,
			&i.Plan,
			&i.ProductType,
			&i.Sku,
			&i.StoreSelected,
			&i.TipoPago,
			&i.Edd1,
			&i.Edd2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
