// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDistinctCanals(ctx context.Context) ([]string, error)
	GetDistinctCompanies(ctx context.Context) ([]string, error)
	GetDistinctFulfillmentTypes(ctx context.Context) ([]sql.NullString, error)
	GetDistinctProductTypes(ctx context.Context) ([]sql.NullString, error)
	GetOrdersByCanal(ctx context.Context) ([]GetOrdersByCanalRow, error)
	GetOrdersByFulfillmentType(ctx context.Context) ([]GetOrdersByFulfillmentTypeRow, error)
	GetOrdersByProductType(ctx context.Context) ([]GetOrdersByProductTypeRow, error)
	GetOrdersWithErrorsCount(ctx context.Context) (int64, error)
	GetTotalOrders(ctx context.Context) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
}

var _ Querier = (*Queries)(nil)
